"""empty message

Revision ID: 6b91071c2279
Revises: b817e46f4070
Create Date: 2018-12-15 21:04:30.767242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b91071c2279'
down_revision = 'b817e46f4070'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('name', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_portfolios_name'), 'portfolios', ['name'], unique=False)
    op.drop_index('ix_portfolios_companyName', table_name='portfolios')
    op.drop_index('ix_portfolios_symbol', table_name='portfolios')
    op.drop_column('portfolios', 'symbol')
    op.drop_column('portfolios', 'exchange')
    op.drop_column('portfolios', 'issueType')
    op.drop_column('portfolios', 'companyName')
    op.drop_column('portfolios', 'industry')
    op.drop_column('portfolios', 'description')
    op.drop_column('portfolios', 'sector')
    op.drop_column('portfolios', 'website')
    op.drop_column('portfolios', 'CEO')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('CEO', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('portfolios', sa.Column('website', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('portfolios', sa.Column('sector', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('portfolios', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('portfolios', sa.Column('industry', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('portfolios', sa.Column('companyName', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('portfolios', sa.Column('issueType', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('portfolios', sa.Column('exchange', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('portfolios', sa.Column('symbol', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_index('ix_portfolios_symbol', 'portfolios', ['symbol'], unique=True)
    op.create_index('ix_portfolios_companyName', 'portfolios', ['companyName'], unique=True)
    op.drop_index(op.f('ix_portfolios_name'), table_name='portfolios')
    op.drop_column('portfolios', 'name')
    # ### end Alembic commands ###
